name: Clippy Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  clippy-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - run: rustup component add clippy

      - name: lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: >
            -- -W clippy::nursery
            -W clippy::pedantic

          # -W clippy::unwrap_used \
          # -W clippy::expect_used \
          # -A clippy::future_not_send \
          # -A clippy::must_use_candidate \
          # -A clippy::missing_errors_doc \
          # -A clippy::unused_async \
