name: Clippy Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  clippy-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # use stable rust
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # lint
      - name: lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
